theme: jekyll-theme-architect

title: [metro-policy]
description: [Subproject of Metro: The WS-Policy implementation for the Metro Web Services stack]

# sidebar links url
links:
  source: https://github.com/javaee/metro-policy
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

